source 'https://rubygems.org'

gem 'rails', '5.0.0'

gem 'sass-rails'
gem "sprockets"

group :development, :test do
  gem "minitest-spec-rails"
  gem "capybara_minitest_spec"
end

gem "reform",      path: "../../../reform"
gem "reform-rails", path: "../../../reform-rails"# ">= 4.1.0"
gem "simple_form"

gem "sqlite3"
