name: CI

on: [push, pull_request]

jobs:
  test-rails5:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: supercharge/mongodb-github-action@1.12.0
      with:
        mongodb-version: "4.4"
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: "2.5"
    - run: BUNDLE_GEMFILE=Gemfile-rails5 bundle install
    - run: BUNDLE_GEMFILE=Gemfile-rails5 bundle exec rake

  test-rails6-ruby2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: supercharge/mongodb-github-action@1.12.0
      with:
        mongodb-version: "4.4"
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: "2.6"
    - run: BUNDLE_GEMFILE=Gemfile-rails6-ruby2 bundle install
    - run: BUNDLE_GEMFILE=Gemfile-rails6-ruby2 bundle exec rake

  test-rails6-ruby3:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: supercharge/mongodb-github-action@1.12.0
      with:
        mongodb-version: "4.4"
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.0"
    - run: BUNDLE_GEMFILE=Gemfile-rails6-ruby3 bundle install
    - run: BUNDLE_GEMFILE=Gemfile-rails6-ruby3 bundle exec rake

  test-rails7_0:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: supercharge/mongodb-github-action@1.12.0
      with:
        mongodb-version: "4.4"
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.0"
    - run: BUNDLE_GEMFILE=Gemfile-rails7.0 bundle install
    - run: BUNDLE_GEMFILE=Gemfile-rails7.0 bundle exec rake

  test-rails7_1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: supercharge/mongodb-github-action@1.12.0
      with:
        mongodb-version: "4.4"
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.2"
    - run: BUNDLE_GEMFILE=Gemfile-rails7.1 bundle install
    - run: BUNDLE_GEMFILE=Gemfile-rails7.1 bundle exec rake

  test-rails7_2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: supercharge/mongodb-github-action@1.12.0
      with:
        mongodb-version: "4.4"
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.3"
    - run: BUNDLE_GEMFILE=Gemfile-rails7.2 bundle install
    - run: BUNDLE_GEMFILE=Gemfile-rails7.2 bundle exec rake

  test-rails8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: supercharge/mongodb-github-action@1.12.0
      with:
        mongodb-version: "4.4"
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.3"
    - run: BUNDLE_GEMFILE=Gemfile-rails8 bundle install
    - run: BUNDLE_GEMFILE=Gemfile-rails8 bundle exec rake
